MESSAGE_TYPES = {
    SAVE_SUCCESS: 1,
    SAVE_FAIL: 2,
    MARK_MODE_START: 3,
    MARK_MODE_END: 4,
    COMMENT_MODE_START: 5,
    COMMENT_MODE_END: 6,
    BOOKMARK_TREE_BUILDER_START: 7,
    BOOKMARK_TREE_BUILDER_END: 8,
    MARK_SELECTION: 9
}